language: node_js
node_js:
- 10.15.1
cache: yarn
env:
  global:
  - secure: c5o+G0+ns4jjlvS57NhhynqVqWyw+RDzUbkTToADCn62ymscg894iQKw/JFDtqtJkL1+g2BvGOolf6t/4mZ1GNjpNOHotwVE3o69oCwkidlGd7CubB6YYz2N9YlGccCgH3uua6rxWQO0kUlt/dNDJCXdDJuXhbCetDEejAIlNs3rJoVBz0ztmy4VvvMNoUuO2QS33nwn9urTgHlk7wfpTBQrt9kzH5zK/Ge/mMfygB5OA4kVt1p4QUH9QXilme+TMdoVjFZw0A9DzNdCsHonxnI/0R9mUMYfLHEqdy5Cm6B/RR7B2QEPooKGELBzek+Z+2V903Cxpk0m9BFmdEIy+w6D+JMYqb448jjYzCFfpmLM7k42Vh7bo1I2ARCjTPTzH9CR68QEgBFkznN2vntHdqkFZN+7+t2sq00MnTm10F6ya/hpPWoi20Azshc4g4TEdXhWJkkWKU3TzrEDwruRchtiy/7/MYXFujQXVtEmsiJbemu2OyIMDCMzokudBXvcugizlMRocVrQEOXFuARZQO9paJTn+wqTBBgvB+NKXb6ygFkwF0lT+SAVzhfa81rpcl9cOTKwziLm3tlv9+6unjLxPx60uaa5b+GKAdKwH6VLY+QDWrcdyKcQ6qbNsQiq5lYCIY6fZSaNDljMBne2pXVI24AX3TQt/xAYhd3h7EA=
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
