language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
  - secure: ZM3FxvaBrQwBcW6ySwA54X003Es1oop0XhGUiYTQ6MJPOeyK/YHAnB4Cx2/zNTwvNZIY/gzA5VP4A2ZU90LFmtWhDXuATYEap9XnTGgFPys/0E3CJ7eJyHU3OjsdGFMkKXYNs/BQYEcCQTC4N76fmeRuoyLhwTsp2uRoDpre2pBTiiQcJ97fCWIDC6oSqVKDWY2QgSSPYpmnNWsUmQ+zFWIBMfbiw2+fg0VWfCereYRYOzzgU5chhmQxVUU0mER1x2pa9Gb5axxCHoaadJ/doVp9yUOpaVr1RW8k0gQ6K6u7QvShDsKFysRB1puyqp9z9bEYzSxOjUc6QZbkRehkg4fE4f8fL1OptDt9E0uliJtDDXlihCB/7fgW5qV65niiv7LPNr19U8qDQLGr+YpREgBUvAmObB31tVHNnlXTvCKmD4tGInZhimmsEs8kVMuuV+8RdbY0XBvkm0wUH9UDQ41UUZ5ExSplESlSyrsOUzizIjrg/LGgHeYgLxWNH9X0KBvbpc9QzJNK779hIRpJVYea6TX1vuJxnXM4YGkNQVW6n7DjffYrHwFtRs35BoI2zBQjg6p9kZ5OXFsw1KjZnRfbAjOq+Lt3eIFLBxDkURMPU15MZLT+VQ4NqMI3N9suLWnWHlb3buUgoW4qNekOh6uXxQqI3uN8GX9FqXMWU98=
  - secure: 0l4PdIYXVHF28nT7jZ16uvJ7L78K5UdMcTQRy9AqVm9wlJI7E76O1hmwsGFnJt0InXC7MbC4b90izN0WZVrJ8j75cRQr4FwbJ1YEWff3jtkLSiHiXdtm8wx4Qq07paHQ1uHNtyrBItmKYVKQFuwkuTQ4zVhPP2Ym5wO0KGnh2MLbyqQKbnOnTqso2Z0sRtlqNMyxGjDEXyY+wUCzG+/cTYhUBV8CtAr/t87jgNdL7EgqTJ3uvRHJ4jusAsvk+fmuvcvT2bpG1Vs0IjTgzUWb8RC4a+9GSczSlSxUOoIUoOC023h3Y9mYMjtMoy69kXL2CdaiDOs4xdxCK+nm4j0Ec3SUAs+NLBLmzJByLoIfcx1cxknMNUUEAcTL5+7eiwoa6oQis9drmK/ToYeD3pcBRVn8lqzGknhGDFtpNtBJ/UDr7TC/3OeDjU/as+mrXdKYoEBYvPo6vgiCXXFGO5u07w9EC33n16CvdMiqcR0svNG75Tq35PlmK7kqRMscNF6v2+ouMGniIwBQ47i3iStgFYxUETd3+h+nVwJRqkXnVJ27ADK+yAdL5C7LDo04iNTV7FBcDs4U3ai6ooRRIM2a7LaPICjWhvG6o+6e5EQQQkAFneX32P/uLhHeaHEEpwNYw/FA+v0U3jTaCi422oBf3Qkn6lM6lviK2qgKVKq5MdU=
