language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  # using this GH_TOKEN "Deploy token for travis-CI" for this deployment
  github-token: "$GH_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: r/7jYrHt8T2c8OUfpkdwxlYxhxOfEMBEKSZPdh65jBM7yzQ4nz/F4IL6hxLFlXmhh9gd3gHLwN3TFNNlMg4vRVScGmbKy7iYCe/mG1Icyha2c4WIRWG48JUsMBIi78Cc4ypJ/5pLWUTCY3ZJhxPAWyF1L0ZazWwBSz4xsWx9jyQGqUsE6tQsELESIa1NJVtHnl+ydQ/68LX0NX1G0qZMiXTW+iNrRfPvD2SnkkxjdtBmm92Tcs8I02mH9bptxyEo0N3mz74OFO4I6qjUaSpDV9dUj6BNAc7dlnRQGa4k2aNjOISAn/kc+1rOZAH+avHWoekjNMUd5g9WCwUP5rFG0mu+hS5J34plfRYKg8klCtPuj0JK2xJKPcl2gKPs+wNqQSqZzRU3ee+cF3Nt+MY/eIgxJTzSzez0o53MkrgNW+45NCRnPJMEGaCusZAdc/y0W6EGNZxxq0Ku8OB50xWO0U6aKpcX/TBhbibXEpiwev2jRxCVAkesvQTL36rT1+qiRLS/sBAX0ITicvxWeoht5jtFzJbof7ptct1AVvbcMC08q1O5BO1S4Ua97Zmi9f1D/+uuDOCqbflyLEZf7ng29Lii7p8bOACWKXCQWydjeFMmX2Yp/62dAhMB/S7yaDDJxn7TYD3M2xmasPYrwp4XNvTP3FF+h+3mvD84RXNLR/k=
