language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: ifsmvjQ/gtQ74z5jAaGKA7JpiYUX9lvuSwT9aFx8GAC+lGh4YYKAIdt/vxnoPWDAytziJlJtUYR0hkS9I69lF5HT+8NnZF7fBuMFZeeZikrQsbLglPoJT/5tw1r/ZN20HMKr5L629gtqju5vZ5AHK5Cf39JLz0nG8H070aJFaINDG7rzhHxfPTod35cJP5hAX5wnoh/IHRlv4oe46G0bomAWbsn7uB1ccfpfglQyLrl6kot0ofV6UdgUA1to0RDE1CKDSVIsiq/69CGlwLj15GdA38/TBUqSOCZ9sboKD0vAESk0db3AwOhDrARlYX1qbFTnz0nzTfFDgjyH+CLqaQWRrwX1cy6lTryqhirN2zyoj5x7w9egOCIuzyUP71RZ6WpFVQSUxysXco+U3xxht5KWosacRGpCZa7p9bCBsn+g0j8S/10V8hX73FiGvzkdrW8BYKMvI/IIvkjEBgtAO0JLrMznJq1PNdHq1cjngjyNI3VMtfSE3nWwIsPNMUkICyQ/6PnnM3ZgLJXsOWL5bAAfjQ3+FxdelmGq6T1la2uWkcwd5rDtUeA8gxwDw4zeRhb0/B6eL1+Hz+9+SenV4wSjcLArfkKFoFL/LePmTD0GvQ5BTJwtP53De/P886Z71teh6m92FGRuSFiVAU3HrBX2PxNARCHA/P7nFiNw5lM=
