language: node_js
node_js:
- '10.15.1'
# - '8.10.0'
cache: yarn
env:
  global:
    secure: sWp693Q7wOFYPVwArG+olHeUnzEvGMZI9yPGoNNPM7VJ1xDGLOSFlWTVbrk2impuR3ogX/ZkcP5HLYZc2Ge3YTjQl9AqZ2+GuOFPMWpGlosxi8VhSaMwWcKjzgjLthaijrFARbPshGkywLfxmNAjXhVNoFKq/Os7A4fvhz4aAQaOlq/b73zJSqwpuVNdCLC4Lo9CeZT9dUr6vinof5/Fd5x/IPzEhg/WqgktAgRibGAd3TCujTrhAv0voTexlakBXqaYGAuTYZw93C7L+YhJZiJ0Q8ujA/oM07D6941jT7f3sFLpRTBBsgXRhiplBmDJXyk8xKXyN2YxXQWXznsLaSFvZO7R1Y2fC/b5rw5mh9BiWJJlwKCiUIPDe7RbxzhKMKr8LXdcPLonbOoIgaxSjUUiZRqgI3VuDQXtlcOG68toQsSurmbofL26cqvnkc88ZbF36iVm9pfwY5mt1n1jfDRW58dGfYLUhmRxdLJHez2hSHfE5sIgAMo3JjdV14bLzbQ9aO0n0OES6EiK7WyuaZHm5/qsrf15sFpM/tiWqXaP94p51T5C8HkGbJC+g/lI69RpMT5QsQPSBMsot4YsdBBoer6gDn2f6/fM6ZD/yxJo7Ua7F7JUIXAG/BCBS0GynES3pwjY6EFIgAdZ88pISaaXBhmSfNLj3I4XKZs72Ao=
before_install:
# - chmod 755 ./deploy.sh
install:
- yarn install
before_script:
# - git config --global user.email "travis@travis-ci.org"
# - git config --global user.name "Travis"
script:
# - chmod +x ./deploy-ghpages.sh
- yarn build # Change this script to run your production build command
# - chmod +x ./deploy.sh
# - "./deploy.sh"
after_success:
# this "deploy.sh" has code to deploy files generated from vue production build
# - gulp deploy
# - "./deploy.sh"
after_failure:
after_script:
before_deploy:
deploy:
# Standard GH-Pages Deploy  
  provider: pages
  skip-cleanup: true
#   github-token: fd8d095ed53a0c01428a583edf6fa199c0c5fae3  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: dist # Change this to your build directory
  on:
    branch: master
after_deploy: