language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: VWTE1zGsfMcIp9XUmoyyTec8xQaN1lPVJjuoC67FSU6OqfKTsjs1cZ+3A73T+I9PxNWUsThrXQ/1WwC72XHwqhzI4Q7Zut6j1L/umxRgILK6U45PoaRgMolSdI5Kel/t0u204+3sInEV6jHm3WDpNJxMduHF3CfU3G0FIGjQ/lkUz+yMXtyE+k9RUz6aWj/TOpgf4iKBShEKF+tu6EMGryaWXIZJrbhvr+1GUzTrW0TgLu0WSMwOojknw+u/GZVnL8TQtxVisLaeNpT6e4GUJVkFs/zmcT/il0UTFz7NGkokkVLb/rtmTD0CtLc5EIYZIGTj+68RRDO55JqVQHLWEg/hrYmctfAm3LPNEFjntEsUeerHu59tPp95bAMiJVlylZcYsdwdYj9JfpQTcwYiPcQumP2TuGYKhCozQ0YqCX9NR857vpZlR9UzMokFrCVrfp7mkjJ44TGXgTrAI3T4GvsXn8729uO/YRmhNgYU4yzbuCdCBcd7Z+ofuRrfZ219Ylj+dZibqOohlItnoF+0WTJs+XF7b+U0bCCei+WgSjmYUsT1Q+FCwlAOSP3Wu0k53OccarH94Re24C9/J9pblIPK4tHBzZbFL7UikUVCXX6vBwz8ojZxw4I2tt3cKcJ3uMCEwfm3q6FQON2vtUvtK4ADFv1XjzWy+JSgNAMkjZY=
