language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: tAhqKUdNCi2LpQAMHEQd+A9fTIf6xw3xpYPuybjuE8thY85s//C1/dSvO83okED2cm0TMzEdFB/Bpr0vrcLmFyrSVpiX7C1dgUgKZzVDou8o7Bg7r7L9NfZ+I1n/2q5C++Q+1hmxvpf9jz6ONK7dODvRdxxZNco4GtXziNyazfPuaG6ADYRBLd23usVS8Y7tNiIhqkrHZf9YTsowGVMOitkMDHzQinS7Y3azUg6eTbJnb4QAVhD1pNl0Rv3a/9aKJHkp71diqmoCXtLCdoAtaMJeI4eoCjTx+FjLAKvxhrqLWcJEwuGX4Om5vb7FsN3YRl+N24NwNuLb5WIoUtiVtIN/t+b75NYiOi3rX9fryeLRHiE/qCvct7K7OFHifVR31KK8YrzFBLSszaHvxANGAyHm7JDlMR3o5foo1y3IgiAtTKh5r9LfAjRX4hPwcn6biaxV+N8h8KPnbQsvhDcJSC99joESbU1B3sv+8BIJ85T91N8dv6eOtu7mVpLpb1ZkfMeskByehkk7op0Dl8ZTngY1Gx7WEJYQqxT3voIoCrZIxLO8hPVopYVxCV5pt8FA1r/WHehMVrLtzzFRSc5454tCOjcJgeYntc+qS6FLT4obj7s9DpqdekrLqqWHn3CVIMfmm3faYRfJaKWpbZ6jO/aij4cYrglNA1SVicXGAs4=
