language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: 3uScHNHzpgCEzfejHvxja9Qbwb/Mr/M86lK6ktTw9ABrqq01CL9d8i2YbUjJ1FUDyvpP6DjEU4CYoivwidrKf00rW/8cxeMSpBzY2vav78jQaGAFRfaz8mapsVX8PBd45M+nSslkeNlCwhJEX/9UA2COCO0vawldLxw/rzs8BjdK6t6fciKVorD0Vv49QAjvP9r0EDllj0yDybopXo1nt82peN0RTHNg3bG3vAiNzA8py/KKi5YHW9E6ukJm6OfXqFwrvhFurk5msrHZu599Pf+NviH2sY+3GxNKG2x5Gjt3b9amtH8AH+F9ijZLmI++6xJR/Z6e+GNfUmFrHv+u5Esk3YtcC7nM8KEXQJaWEZFBIvEcgvCN0xlqezZzmjN8ldUCoEeCgXYxfwd8RZ/gE3YMnQ3ekqOokX5oc23yuhJZ36A3RsrmYdMpP/7nw+LHJIKn7QXTFQUzDlxRvC7RrFkqZ//waET3uULA/7+b2sgW9kwY6AtKc8eQlBrW5DUPHzdqJ8NTca8EyrULQ2W1BMeX6en4pn8i9VKbi7fCc/wE/awkx+RFp32VfAYWL9K58k6VAhzJxBXKP4HupKhlRXdUgEO35l9/PnDkW6jk2KgHFARTbAyIJjLL9+QV8EfwoBrYi5DlzMyzUWgOePMs0xF+Ij2RHC8ELfn+MMJVgFc=
