language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: 2XgMamWaZbckCcLifhQnotwe2zEqiQI8yVHrkKEkysCDTyIUMlzw4420dgGyS0aXN4XaEKzype2TBhMcbYrIn2StVgMsJXbyjenXqA7uoj17C2FSdJBKOPtecVIuLt4U+EuOJxwXYXqvjdeRbrjctm7aE/ew1jIDaiVeXS5f3ByZbxHeWp8LHXNxGbITdNvG11O9ZGTnyZabBwyXH7dYkeuEUx5rU35K2fW4VoXvQhs/eO28uOGBaQEE0RhZMRADWlXgdgmdnIoH3e4WrWiLDf/OELGyiB3NjcRZ/WKxZFz682lwKdNgQAlFHYdamxxFdZeiQHgnOYFaBU7IZD3JAROfWWrWj48oGTYMeKnU7GKsiK8859S+XPIpG8voBAO+jepCaQXhRaI/nuSj3pkhlgC7GANfWgMtbQDNjeeI0UE9iUw59OgsO39W5ztIMOeDb7oWd73YtqjSf/0omeY7EkNDz3D1vA0oPqY8eloAzVnsjuGRQtTmNsquMMn0kyf4g0hHGcut2Kn+yt2Vbhh+R3SKtxOSNVwPbC60nbzmKgwySIrT/EYxWP5k7+7JK477vIddh9f92qdrJOBeN+uFYWluQD5gVQtX9X/ta3oTsCshgAeRgx4i00TAmxwYcE3dj+DvIlbHqgECJwvmvtoKVFoMWRZYNnwLIKChyxe3v64=
