language: node_js
node_js:
- 10.15.1
cache: yarn
before_install: 
install:
- yarn install
before_script: 
script:
- yarn build
after_success: 
after_failure: 
after_script: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy: 
env:
  global:
    secure: ICgCVvqr1izHBXI7MRgYTq7Et6LIhj/UWJa6q5gRUPOmn2jFv/MYbsHpd7OFlFf0eltuNb499St02H/bEGFhrWc+qWeYevXQdrdUwF0ymyJzXP4Fz9PL122197TommbC7hQmxCZXLgCxpD+NZ8HmjWFJtlHKBc/pFkYVf9JqzcNZB8onOjviMCbz1pkQ6nVuH2w9sNgNzIhsQgQjp6oBAYUawRxxvl6k7JyKFEth8BTQvb2XuOE81kCMYYfNc58xlz9DxuinNH0fNBRF7kYeF8FymBnn8vFcnmK6N4FdJ4geuN2tQOvmMsHVaJrzYRHj6icKBFR69eVUe6B5HLn60QgIKBEsZSzjEVyHgUyp4tqi/G6t9R22RKJygDsGNBTymcxF1zpXS9GUUu5r/EeZQPno2GNfzcTnarrMIDtLTPch3uVsihsL8kXPuWHEdh8EbbcAGmVz/0xbnvBCD2grhASR0hiBdZCiLDrOgJ+Aop/bpVxk+I5LtAihyRxNEK/FoqimqRZJvIVNkCCcOJfSZA9AP8o89qe9ZUP6oAzOIlZJupZaSJUtVtp6Y5/+e2Ueg4+HsSeD0Ce8Lb8ZslZeYaEeaUAVYs/SUFzxjR44Z2ezGiMF8dafLIRlgcCszvwgNJFHenNnOKmDAU2Xmnz7E4eEF1wJA+R+SS9vDtAO848=
